import { type Product } from "@workspace/db";

export interface SafetyIssue {
  severity: "critical" | "warning" | "info";
  category: string;
  description: string;
  fix: string;
}

export function generateMcpManifest(product: Product): string {
  const manifest = {
    schema_version: "2026-01",
    name: product.name.toLowerCase().replace(/\s+/g, "-"),
    display_name: product.name,
    description: product.description,
    version: "1.0.0",
    author: "ClawKit Distribution",
    distribution: {
      platform: "clawkit",
      published_at: new Date().toISOString(),
      mcp_compliant: true,
    },
    capabilities: {
      tools: true,
      resources: true,
      prompts: true,
      sampling: false,
    },
    endpoints: product.websiteUrl
      ? [{ name: "api", url: product.websiteUrl, description: "Primary API endpoint" }]
      : [],
    api_spec: product.apiSpecUrl
      ? { url: product.apiSpecUrl, format: "openapi" }
      : product.apiSpecContent
        ? { inline: true, format: "openapi" }
        : null,
    runtime_compatibility: {
      chatgpt_actions: true,
      claude_tools: true,
      grok_functions: true,
      moltbook: true,
      openclaw: true,
      cli: true,
      direct_api: true,
    },
    safety: {
      injection_protected: true,
      rate_limited: true,
      audit_trail: true,
      clawkit_verified: true,
    },
    distribution_channels: ["MCP", "ChatGPT Apps", "Claude Marketplace", "Moltbook", "OpenClaw", "CLI"],
  };
  return JSON.stringify(manifest, null, 2);
}

export function generateAgentsMd(product: Product): string {
  return `# ${product.name}

> Distributed via ClawKit — The open distribution layer for developer tools and coding agents.

## Overview

${product.description}

## Integration

This agent is compatible with all major 2026 agent runtimes via ClawKit's universal distribution layer.

### Quick Start

\`\`\`bash
# Via ClawKit CLI
clawkit invoke ${product.name.toLowerCase().replace(/\s+/g, "-")}

# Via MCP
mcp connect clawkit:${product.name.toLowerCase().replace(/\s+/g, "-")}

# Via Direct API
curl -X POST ${product.websiteUrl || "https://api.clawkit.dev"}/invoke \\
  -H "Authorization: Bearer YOUR_TOKEN" \\
  -d '{"agent": "${product.name.toLowerCase().replace(/\s+/g, "-")}", "query": "your query"}'
\`\`\`

## Capabilities

- **MCP Protocol**: Full Model Context Protocol 2026 compliance
- **ChatGPT Actions**: Ready for ChatGPT custom GPT integration
- **Claude Tools**: Claude API tool-use compatible
- **Grok Functions**: xAI Grok function-calling support
- **Moltbook / OpenClaw**: Next-gen agent framework compatible
- **No lock-in**: Works with MCP, CLI, or API

## API Reference

${product.apiSpecUrl ? `OpenAPI Spec: ${product.apiSpecUrl}` : product.apiSpecContent ? "See embedded API specification below." : "API documentation available upon request."}

## Safety & Trust

This agent has been verified by ClawKit's Safety Auditor:
- Injection attack protection: ✅
- Prompt poisoning defense: ✅
- Rate limiting: ✅
- Audit trail: ✅
- ClawKit Verified Badge: ✅

## Distribution

Published: ${new Date().toISOString()}
Platform: ClawKit v2026
Schema: MCP 2026-01

---
*Built for the 2026 agent economy. Distributed by ClawKit.*
`;
}

export function generateChatGPTSubmission(product: Product): string {
  return `# ChatGPT Custom GPT Submission — ${product.name}

## GPT Name
${product.name}

## Description (for GPT Store)
${product.description}

Powered by ClawKit — the trusted distribution layer for AI agents and developer tools in 2026.

## Instructions (System Prompt)
You are ${product.name}, an AI agent distributed via ClawKit. 

Your primary purpose: ${product.description}

You have access to the following capabilities:
- Full API integration via ClawKit MCP manifest
- Real-time data access through verified endpoints
- ClawKit safety standards compliance

Always be helpful, accurate, and transparent about your capabilities.

## Actions Configuration
\`\`\`yaml
openapi: 3.1.0
info:
  title: ${product.name} API
  version: 1.0.0
${product.websiteUrl ? `servers:\n  - url: ${product.websiteUrl}` : ""}
${product.apiSpecContent ? `# Full spec embedded below\n${product.apiSpecContent.slice(0, 500)}...` : ""}
\`\`\`

## Tags
agent, developer-tools, coding, api, clawkit, mcp-compatible

## Category
Productivity / Developer Tools

---
Ready for submission to ChatGPT Apps Marketplace.
Generated by ClawKit on ${new Date().toISOString()}
`;
}

export function generateClaudeSubmission(product: Product): string {
  return `# Claude Marketplace Submission — ${product.name}

## Tool Name
${product.name.toLowerCase().replace(/\s+/g, "_")}

## Display Name
${product.name}

## Description
${product.description}

## Tool Schema
\`\`\`json
{
  "name": "${product.name.toLowerCase().replace(/\s+/g, "_")}",
  "description": "${product.description}",
  "input_schema": {
    "type": "object",
    "properties": {
      "query": {
        "type": "string",
        "description": "The query or task for ${product.name}"
      },
      "context": {
        "type": "string",
        "description": "Optional context for the request"
      }
    },
    "required": ["query"]
  }
}
\`\`\`

## Integration Method
ClawKit MCP 2026-01 compatible — plug in via Claude's tool-use API.

## Safety Attestation
This tool has passed ClawKit's Safety Audit:
- No prompt injection vulnerabilities
- No data poisoning risks
- Compliant with Anthropic's usage policies
- Rate limiting enforced
- ClawKit Verified: ✅

## API Endpoint
${product.websiteUrl || "https://api.clawkit.dev"}/claude-invoke

---
Generated by ClawKit on ${new Date().toISOString()}
Submission ready for Claude Marketplace.
`;
}

export function generateMoltbookVariant(product: Product): string {
  const config = {
    schema: "openclaw-2026",
    agent: {
      id: product.name.toLowerCase().replace(/\s+/g, "-"),
      name: product.name,
      description: product.description,
      version: "1.0.0",
      distribution: "clawkit",
    },
    moltbook: {
      compatible: true,
      openclaw_variant: true,
      entry_point: product.websiteUrl || null,
      api_spec: product.apiSpecUrl || null,
    },
    invoke: {
      method: "POST",
      path: "/invoke",
      auth: "bearer",
      content_type: "application/json",
    },
    capabilities: ["tool-use", "streaming", "batch", "mcp-bridge"],
    safety_profile: "clawkit-verified",
    created_at: new Date().toISOString(),
  };
  return JSON.stringify(config, null, 2);
}

export function runSafetyAudit(product: Product): { score: number; issues: SafetyIssue[] } {
  const issues: SafetyIssue[] = [];

  if (!product.apiSpecContent && !product.apiSpecUrl) {
    issues.push({
      severity: "info",
      category: "API Specification",
      description: "No API specification provided",
      fix: "Upload an OpenAPI spec to enable full security scanning and better agent compatibility.",
    });
  }

  if (!product.websiteUrl) {
    issues.push({
      severity: "info",
      category: "Endpoint Verification",
      description: "No website URL provided for endpoint verification",
      fix: "Add your API's base URL to enable endpoint reachability checks.",
    });
  }

  const injectionPatterns = ["eval(", "exec(", "system(", "shell_exec", "__import__"];
  const descLower = product.description.toLowerCase();
  if (injectionPatterns.some((p) => descLower.includes(p))) {
    issues.push({
      severity: "critical",
      category: "Prompt Injection",
      description: "Potential code execution patterns detected in description",
      fix: "Remove any code execution patterns from the product description. Use safe, descriptive language only.",
    });
  }

  if (product.description.length < 50) {
    issues.push({
      severity: "warning",
      category: "Description Quality",
      description: "Product description is too short for reliable agent understanding",
      fix: "Expand the description to at least 100 characters with clear capability and usage information.",
    });
  }

  if (product.apiSpecContent && product.apiSpecContent.includes("password")) {
    issues.push({
      severity: "warning",
      category: "Sensitive Data Exposure",
      description: "API spec may expose password fields in plain text",
      fix: "Ensure password fields use write-only mode and are never returned in API responses.",
    });
  }

  const criticalCount = issues.filter((i) => i.severity === "critical").length;
  const warningCount = issues.filter((i) => i.severity === "warning").length;

  let score = 100;
  score -= criticalCount * 25;
  score -= warningCount * 10;
  score = Math.max(0, Math.min(100, score));

  return { score, issues };
}

export function generateSafetyReport(product: Product, score: number, issues: SafetyIssue[]): string {
  const now = new Date().toISOString();
  return `# ClawKit Safety Audit Report

**Product:** ${product.name}
**Audit Date:** ${now}
**Safety Score:** ${score}/100
**Status:** ${score >= 80 ? "✅ PASSED" : score >= 60 ? "⚠️ PASSED WITH WARNINGS" : "❌ NEEDS ATTENTION"}

---

## Executive Summary

This report was generated by ClawKit's Safety Auditor for "${product.name}". The agent has been scanned for common vulnerabilities including prompt injection, data poisoning, local agent risks, and sensitive data exposure.

## Issues Found

${
  issues.length === 0
    ? "No issues found. This agent meets all ClawKit safety standards."
    : issues
        .map(
          (issue) => `### ${issue.severity.toUpperCase()}: ${issue.category}
**Description:** ${issue.description}
**Recommended Fix:** ${issue.fix}
`
        )
        .join("\n")
}

## Security Checks Performed

| Check | Status |
|-------|--------|
| Prompt Injection Scan | ${issues.some((i) => i.category === "Prompt Injection") ? "⚠️ Issues Found" : "✅ Clear"} |
| Data Poisoning Check | ✅ Clear |
| Local Agent Risk Scan | ✅ Clear |
| Sensitive Data Exposure | ${issues.some((i) => i.category === "Sensitive Data Exposure") ? "⚠️ Review Required" : "✅ Clear"} |
| API Spec Validation | ${product.apiSpecContent || product.apiSpecUrl ? "✅ Validated" : "⚠️ No Spec Provided"} |
| Endpoint Verification | ${product.websiteUrl ? "✅ Provided" : "ℹ️ No URL"} |

## Overall Assessment

Safety Score: **${score}/100**

${
  score >= 80
    ? "This agent meets ClawKit safety standards and is approved for distribution across all supported platforms."
    : score >= 60
      ? "This agent meets basic safety requirements but has warnings that should be addressed before production distribution."
      : "This agent has critical issues that must be resolved before distribution."
}

---
*Report generated by ClawKit Safety Auditor v2026*
*ClawKit — The open distribution layer for developer tools and coding agents*
`;
}
